### ISSUE TITLE
Octoprint git pull doesn't work

### ISSUE THREAD

**Issue by nophead** [guysoft/OctoPi#74] opened 2015-02-26 14:21 UTC
Freshly installed OctoPi 2015-01-31-octopi-0.11.0-2015-02-13.zip
```
cd OctoPrint/
git pull
error: Failed connect to gnet.homelinux.com:80; Connection timed out while accessing http://gnet.homelinux.com/git/OctoPrint.git/info/refs
fatal: HTTP request failed

git remote -v
origin  http://gnet.homelinux.com/git/OctoPrint.git (fetch)
origin  http://gnet.homelinux.com/git/OctoPrint.git (push)
```
Shouldn't the remote point to https://github.com/foosel/OctoPrint.git ?

**Comment by korneelb** [comment] 2015-02-26 15:22
i have the same issue with the latest daily builds..

**Comment by nophead** [comment] 2015-02-26 16:08
This fixed it for me
```
git remote rm origin
git remote add origin https://github.com/foosel/OctoPrint.git
git pull origin master
```

**Comment by korneelb** [comment] 2015-02-28 10:11
this did not fix it for me.. i can't pull the latest builds. still getting some errors.

**Comment by nophead** [comment] 2015-02-28 10:15
What sort of errors?

Note the latest OctoPrint is the devel branch, master is the stable one.

**Comment by korneelb** [comment] 2015-02-28 14:35
so the actuall correct fix is
cd ~/OctoPrint
git config --get remote.origin.url  (this will show you the gnet.homelinux.com url) 
git config --replace-all remote.origin.url https://github.com/foosel/OctoPrint.git

run the --get again to verify your change.

**Comment by nophead** [comment] 2015-02-28 14:51
Strange, my fix gives the same end result, so I don't know why it didn't work for you:
```
git config --get remote.origin.url
https://github.com/foosel/OctoPrint.git
```

**Comment by guysoft** [comment] 2015-03-02 13:25
Ok its caused by no cding in the the folder in the command ``git remote set-url``:
Getting in the build: ``Not a git repository (or any of the parent directories): .git``

**Comment by guysoft** [comment] 2015-04-04 12:45
Should be fixed next nightly

**Comment by guysoft** [comment] 2015-04-04 16:16
Should be fixed next nightly

**Comment by guysoft** [comment] 2015-04-09 10:39
Still not there, added another fix

**Comment by guysoft** [comment] 2015-04-11 13:59
Fix in last nightly

**Closed by guysoft** 2015-04-11 13:59 UTC
Labels: bug

**Comment by foosel** [comment] 2015-06-26 07:33
Just for the record, one simple line should actually be enough to fix the URL:

    git remote set-url origin https://github.com/foosel/OctoPrint.git

See also [here](https://help.github.com/articles/changing-a-remote-s-url/)
