### ISSUE TITLE
Armbian support

### ISSUE THREAD

**Issue by agreen** [guysoft/OctoPi#406] opened 2017-08-29 01:25 UTC
I saw that as of 1.4 you have Armbian support. I tried over 50x to run the build for an orange pi zero, with the image in the end not working on the orange pi zero.  I tried the build on a (freshly created) ubuntu xenial desktop install. I also tried the vagrant build with little/no difference in luck. ~40 of the 50 attempts were due to pip failing to find modules that clearly exist... (I have 30mbps cable).

I'm working on documenting some of the minor changes I had to make to get it to do anything, but before I dive too deep, I just wanted to touch bases with you to see if you have any advice/updates I should try first.

**Comment by guysoft** [comment] 2017-09-10 23:36
Duplicate of #232 also see https://github.com/guysoft/CustomPiOS/pull/2

**Closed by guysoft** 2017-09-10 23:36 UTC
