### ISSUE TITLE
PI0W built in wifi

### ISSUE THREAD

**Issue by CamoJackson** [guysoft/OctoPi#331] opened 2017-03-30 14:02 UTC
Can you add support for the built in wifi adapter on the pi0 W i couldn't get it to work for me

**Comment by realzeus** [comment] 2017-04-03 08:34
Is it a duplicate of #318 "OctoPi 0.13 does not work with Pi Zero W" ?

**Comment by foosel** [comment] 2017-04-03 10:39
Yep, duplicate.

**Closed by foosel** 2017-04-03 10:39 UTC
