### ISSUE TITLE
cannot connect to university wifi

### ISSUE THREAD

**Issue by nortonw3** [guysoft/OctoPi#329] opened 2017-03-29 00:15 UTC
I go to Baylor university and I am trying to set up my new printer with octoprint, however, I can only run my octopi through the wifi hotspot on my phone because the wifi here uses username and password to connect. it is supposedly a wlan2 connection but I have no idea what to add to the octopi-network.txt file to log into my network. Thanks for the help!

**Comment by guysoft** [comment] 2017-03-30 08:49
Duplicate of https://github.com/guysoft/OctoPi/issues/301

**Closed by guysoft** 2017-03-30 08:49 UTC
