### ISSUE TITLE
Integrating AI based print failure detection / Data collection

### ISSUE THREAD

**Issue by maxupp** [guysoft/OctoPi#693] opened 2020-11-06 14:41 UTC
An AI plugin that detects failed prints on the webcam feed would be great.

I'd like to develop it, but I do not have the data.  I think OctoPi itself could collect the data with a simple "contribute" button, which grabs and uploads images of regular and failed prints. If this is of interest I'll make a pull request for the UI element and upload functionality.

**Comment by guysoft** [comment] 2020-11-06 14:47
You likely need to talk to @foosel on OctoPrint, OctoPi could ship with a plugin and the libs needed. B
But you would need this to work on OcoPrint first.
There was an attempt already with https://www.thespaghettidetective.com/ . But it closed source and they keep the data which is something I am against since both OctoPi and OctoPrint are AGPL license.

Closing ad duplicate of: https://github.com/OctoPrint/OctoPrint/issues/1256
(which I suggest you post in your interest to develop this).

**Closed** 2020-11-06 14:47 UTC
