### ISSUE TITLE
OctoPiPanel login loop

### ISSUE THREAD

**Issue by totalyfrozen** [guysoft/OctoPi#278] opened 2016-11-23 01:53 UTC
installed Octopi onto my Raspberry Pi 3 raspbian jessie and I am stuck in this login loop on the GUI. Im using the Raspberry Pi 7" touch screen. granted I can us the Octoprint portion just fine, I was just trying to get the screen to work on the Pi. I have tried pretty much all I could find on this issue without any luck.. just pops up the log in screen, I enter my password, screen goes blank, then pops again to enter my password. 

Hope someone can help me out with this. pretty new to all this. 

thanks

**Comment by guysoft** [comment] 2016-11-23 13:45
This is an OctoPiPanel issue, and is a duplicate of https://github.com/jonaslorander/OctoPiPanel/issues/51

**Closed by guysoft** 2016-11-23 13:45 UTC
