### ISSUE TITLE
Cannot delete files from web interface Version 1.3.0

### ISSUE THREAD

**Issue by mboyet** [guysoft/OctoPi#288] opened 2017-01-04 05:00 UTC
Sine the update I cannot delete files I have uploaded via the web interface.  Log attached.
[octoprint.txt](https://github.com/guysoft/OctoPi/files/683957/octoprint.txt)

**Comment by guysoft** [comment] 2017-01-11 12:04
1. this is a duplicate of #282 
2. This is an Octoprint, issue, not an OctoPi issue, and is already in talks at https://github.com/foosel/OctoPrint/issues/1637

**Closed by guysoft** 2017-01-11 12:04 UTC

**Comment by mboyet** [comment] 2017-01-14 02:08
Thanks, Guy
