### ISSUE TITLE
[BUG] Problems with 'Build OctoPi From within OctoPi '

### ISSUE THREAD

**Issue by jiantaolovebingbing** [guysoft/OctoPi#652] opened 2020-06-07 03:10 UTC
#### What were you doing?

1. Just follow the readme file the 'Build OctoPi From within OctoPi / Raspbian / Debian / Ubuntu' part
2. in last step, it reports an error

#### What did you expect to happen?
The build.log file is  showed as below .
[build1.log](https://github.com/guysoft/OctoPi/files/4741339/build1.log)

#### Version of OctoPi
OctoPi 0.17.0
pi 3 model B+

#### Screenshot(s)/video(s) showing the problem:

[Uploading build1.log…]()

I have read the FAQ.

**Comment by guysoft** [comment] 2020-06-07 16:23
Entry from build.log:
```
losetup: /dev/loop0: detach failed: No such device or address
```
Duplicate of https://github.com/guysoft/CustomPiOS/issues/55

Try running again. The issue is a bug in Docker (which its good you are using) where it does not update in time the loopback devices. It tends to fail once, then work on the next run.

**Closed by guysoft** 2020-06-07 16:23 UTC

**Comment by jiantaolovebingbing** [comment] 2020-06-08 04:00
sorry, upload wrong file.
[buildPi.log](https://github.com/guysoft/OctoPi/files/4743778/buildPi.log)

**Comment by guysoft** [comment] 2020-06-09 22:06
This issue has been opened at: #653 Please comment there
