### ISSUE TITLE
octopi.local stopped working?

### ISSUE THREAD

**Issue by stevelucky** [guysoft/OctoPi#93] opened 2015-05-08 15:11 UTC
I just installed Octopi for the first time yesterday and all aspects of it were working great. Then, seemingly out of nowhere, I couldn't connect to it via octopi.local. I pulled the SD card and did a full reinstall just in case somehow I messed something up but I still couldn't connect. Finally, I tried connecting via my Raspberry Pi IP address and it connected great. So, for some reason, I just can't connect via octopi.local. Any idea what the issue could be?

EDIT: How do I delete this thread? I finally saw that someone else had this same issue. I don't want to have a duplicate thread.

**Comment by stevelucky** [comment] 2015-05-08 15:12
How do I delete this thread? I finally saw that someone else had this same issue. I don't want to have a duplicate thread.

**Comment by stevelucky** [comment] 2015-05-08 15:18
Though, I guess if you want to leave it up, I can post my solution. I just edited my hosts file to redirect the IP address to octopi.local. Looked like this:

192.168.1.XXX  octopi.local

After adding that, it worked just fine.

**Comment by guysoft** [comment] 2015-06-03 08:41
Sounds like something with your router setup

**Comment by foosel** [comment] 2015-07-05 13:17
Duplicate of #56, closing add already requested by op

**Closed by foosel** 2015-07-05 13:17 UTC
