### ISSUE TITLE
Upgrade existing OctoPi installation

### ISSUE THREAD

**Issue by tiagojanz** [guysoft/OctoPi#64] opened 2015-02-09 09:05 UTC
Hi is it possible to upgrade the existing octopi installation?
I know I could just download a new nightly but I have to compile a new Kernel to give support for touchscreen EGalax and it takes a day to get it done :( .

**Comment by guysoft** [comment] 2015-02-09 09:31
Duplicate of #4
There are instructions there how to upgrade manually ;)

**Closed by guysoft** 2015-02-09 09:31 UTC
