### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by jminardi** [guysoft/OctoPi#214] opened 2016-03-19 17:40 UTC
Recently my OctoPi builds have been failing with a locale error. This is with no change on my end, one day it worked, the next it was failing.

Here is the error:

```python
+ sudo -u pi /home/pi/oprint/bin/pip install ndg-httpsclient pyasn1
sudo: unable to resolve host ubuntu
Traceback (most recent call last):
  File "/home/pi/oprint/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/home/pi/oprint/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by guysoft** [comment] 2016-03-19 18:14
What image are you building against?
Because I don't get this error on raspbian jessie but I do get it in the bananapi variant. It seems to happen because the locale used is missing in the image

**Comment by jminardi** [comment] 2016-03-19 18:27
I have been using 2016-02-09-raspbian-jessie

**Comment by jminardi** [comment] 2016-03-19 18:28
I had previously been getting a bunch of perl locale warning but they didn't seem to cause any problems:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by jminardi** [comment] 2016-03-19 20:15
Just tried2016-03-18-raspbian-jessie 

same problem

**Comment by guysoft** [comment] 2016-03-19 20:39
Can you try using the vagrant build method provided in the readme? That should make sure your build environment is the same as mine.

**Comment by jminardi** [comment] 2016-03-19 21:15
After more digging I figured the error must be in a recent pip. I tried installing pip 8.0.3 instead of the latest and it fixed the problem.

I can try the vagrant build and will report back

**Comment by guysoft** [comment] 2016-03-20 09:42
Confirmed, it started happening on my builds too.

Can you post your current fix.

**Comment by guysoft** [comment] 2016-03-20 10:03
Adding ``export LC_ALL=C`` at the start of the chroot script seems to fix it, running a new nightly build to test it and if that works it would be committed in an hour or so.

**Closed** 2016-03-20 13:26 UTC
Labels: bug
