### ISSUE TITLE
competition. 

### ISSUE THREAD

**Issue by rewolff** [guysoft/OctoPi#399] opened 2017-08-12 06:08 UTC
http://www.gocomics.com/theargylesweater/2017/08/12

**Comment by guysoft** [comment] 2017-08-12 09:58
Can't reproduce.
Maybe this workaround might work: https://www.thingiverse.com/thing:10337

**Comment by guysoft** [comment] 2018-02-24 12:25
![fb_img_1519298160967](https://user-images.githubusercontent.com/325670/36630412-96509df0-196e-11e8-8498-47c35b5214d5.jpg)

**Comment by guysoft** [comment] 2019-07-02 15:50
No one is funny anymore, closing.

**Closed by guysoft** 2019-07-02 15:50 UTC
