### ISSUE TITLE
Camera can be accessed even if not logged in

### ISSUE THREAD

**Issue by FredClement91** [guysoft/OctoPi#440] opened 2017-11-21 18:28 UTC
Hi,
Access control is great, but not very usefull as the camera stays still available even if not logged in.
To my mind, it shouldn't be.
For the rest, all is working very fine for me.

Fred

**Comment by guysoft** [comment] 2017-11-21 23:10
Duplicate of #/292

**Closed by guysoft** 2017-11-21 23:10 UTC
