### ISSUE TITLE
Cant connect to my printer Monoprice Select Mini V2

### ISSUE THREAD

**Issue by AirWalker06** [guysoft/OctoPi#398] opened 2017-08-09 17:14 UTC
I cant connect to my printer it gives me:
Changing monitoring state from 'Offline' to 'Detecting serial port'
Serial port list: ['/dev/ttyACM0', '/dev/ttyACM0']
Connecting to: /dev/ttyACM0
Error while connecting to /dev/ttyACM0: 'Timeout'
Connecting to: /dev/ttyACM0
Error while connecting to /dev/ttyACM0: 'Timeout'
Changing monitoring state from 'Detecting serial port' to 'Error: Failed to autodetect serial port, please set it manually.'
Failed to autodetect serial port, please set it manually.

I do lsusb and it gives me this:
![image](https://user-images.githubusercontent.com/4444669/29134434-98d21970-7d04-11e7-8526-fa5a3ce65883.png)

Im using the newest model of the raspberry pi as well as all the firmware updated to the current versions.

**Comment by guysoft** [comment] 2017-08-09 17:25
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/

**Comment by guysoft** [comment] 2017-09-24 10:46
Duplicate of #392

**Closed by guysoft** 2017-09-24 10:46 UTC
