### ISSUE TITLE
Raspberry Pi Camera V2.1 module won't work with Octoprint

### ISSUE THREAD

**Issue by SeventhDread** [guysoft/OctoPi#588] opened 2019-05-04 14:15 UTC
I have plugged in my camera won't come up I have tried everything I have connect the 15 pin cable in the right way I am completely new to this so please answer as simply as you can I have tried all sorts of things so please talk me through step by step (With pictures if you can) like from the very start with a blank micro SD, Raspberry Pi 3 B and a Raspberry Pi Camera Module V2.1 please I really want this to work (Ask me any additional questions if needed)

**Comment by tedder** [comment] 2019-05-04 15:45
Seventh, there are plenty of walkthroughs. Google it and find one that fits your learning style.

**Comment by John-Mc** [comment] 2019-05-04 16:11
This site is focused mainly on bug reports, not on providing “how-to” assistance. 

You might try searching (or posting) on https://community.octoprint.org/. That site is focused more on providing support, including for set-up issues such as yours.

**Comment by guysoft** [comment] 2019-05-05 08:36
Thanks @tedder and @John-Mc for pointing @SeventhDread to the right place in my absence. Closing, this is not a bug, a community question for https://community.octoprint.org/

**Closed by guysoft** 2019-05-05 08:36 UTC
