### ISSUE TITLE
Octopi reports 7 days print time for 30+ hour print

### ISSUE THREAD

**Issue by T3DT** [guysoft/OctoPi#357] opened 2017-05-20 14:46 UTC
Scary print Time Reporting From OctoPi

Octopi stable version 0.13 - 1.3.2 (stable) 
with:-
OctoPrint-Slic3r Plugin: 1.1.0 installed.

Installed on a Rasberry Pi B v1 with 16GB stick 

 OctoPrinti Web interface text capture:-
State: Printing
File: 2-Hexagon-2-33h22.gcode 
Timelapse: Timed (15 sec)
Approx. Total Print Time: -
Print Time: 00:37:24
Print Time Left: 7 days ●
Printed: 169.2KB / 49.1MB

A gcode file was uploaded to Octopi (dragged and dropped on web interface) 
Gcode file was produced on Cura 15.04.4 on Windows 7.

I suspect anything that has a print time > than 24 hours will reproduce the same error.

Side note to this problem report
A Gcode file was uploaded as the octopi Cura 15.04.4 plugin crashed while slicing the :- 
Ultrascope 2-Heagon-2.stl on a Pi B v1 could not slice It is a very big Stl file

Print Time: 00:36:59
Print Time Left: 7 days ●

**Comment by guysoft** [comment] 2017-05-21 13:37
Not am OctoPi bug, its an Octoprint issue.
Duplicate of https://github.com/foosel/OctoPrint/issues/1428

**Closed by guysoft** 2017-05-21 13:37 UTC
