### ISSUE TITLE
Daily builds can't run 250000 baud rate

### ISSUE THREAD

**Issue by korneelb** [guysoft/OctoPi#84] opened 2015-03-24 09:15 UTC
tried this on a raspberry pi B, raspberry pi B+ and raspberry Pi 2.

when using the daily builds and trying to use the 250000 baud rate i get the old octoprint bug 222, can't open serial port.
using the latest stable build works. 

tried the latest stable from februari;
default image - works
running rpi-update and reboot - works
running apt-get update and apt-get upgrade and reboot - works
git pull to Version: 1.2.0-dev-668-g3ebd54d (devel branch) - works

so it's something in the OctoPi distribution..

**Comment by foosel** [comment] 2015-03-24 09:20
Encountered this for some of the nightly builds at work as well. The fix was to add the `python-serial` package to the packages being `apt-get remove`d in `chroot_script`.

The reason appears to be that since the virtual env is created including site packages but then gets its own version of pyserial as well, sometimes the site package one is used, sometimes the local one. I was not able to figure out why that was happening, but just getting rid of the site package (which we don't want need anyways) solved it for good.

**Comment by guysoft** [comment] 2015-03-24 15:00
Merged, please try out the next nightly (starts building only tonight).
Should be build number 94. You can follow progress here: http://gnet.homelinux.com:8080/job/OctoPi/

**Comment by guysoft** [comment] 2015-03-30 15:26
Cam someone with a 250000 baud rate confirm this is indeed fixed?

**Comment by seefood** [comment] 2015-03-30 18:06
I could not with the 1.0.2 merge (what we call "our RBCE" I guess. we need to give it a name). I'm giving a try to the my Development+Rigidboard branch. if it seems to work, I'll try to pull it up to 250000 if you want.

but I still don't see the point. at the speed the step motors are able to move the head, even 38400 should be speedy enough, it's really not that important...

**Comment by guysoft** [comment] 2015-03-30 18:14
Its important for people who can't modify the firmware so freely. Not to mention its a regression. Regressions are not good.

@korneelb ?

**Comment by korneelb** [comment] 2015-03-30 18:14
well, certain printers, like the ultimaker 2, only accept 250000 baud,..

**Comment by guysoft** [comment] 2015-03-30 18:17
Oh, didn't know ultimaker 2 is like that. If anyone with an ultimaker 2 can report the nightly works it would be nice to close this issue.

**Comment by foosel** [comment] 2015-03-30 18:19
@seefood before the stepper motors can move at all, you have to get the data to the firmware, which wants to fill some buffers in order to properly plan ahead its moves. If you have something with a lot of short moves (and hence a lot of lines which don't generate a lot of real movement, but still are at least something like `N384 G1 X20.3 Y83.4 F300*483` <- this long, you can quickly run into issues with low baudrates.

**Comment by seefood** [comment] 2015-03-30 18:25
Well, right now, my Development "bleeding edge" branch is not working, I am back to the Marlin 1.0.2 plus Rigid and both are working only at 115200. As for Ultimaker - that's not our scope, the branch in question is only for RigidBoard.

I'll see if I can figure this out once I dive into the code, but that is going to take a few days/weeks....

**Comment by nallath** [comment] 2015-03-31 15:38
Pyserial is rather rubbish when it comes to being updated. The problem with certain baudrates not being recognised is from 2012 (!!!). 
Doesn't octoPi auto detects the baudrate? Cura uses a fairly nasty way of doing it, but it does work. It simply tries all common baud rates, sends some commands and if the response makes sense, it has to be the correct baud rate.

**Comment by guysoft** [comment] 2015-04-23 08:06
According to #89 this is fixed.
You guys didn't pst this us fixed :-/

**Closed by guysoft** 2015-04-23 08:06 UTC
Labels: bug

**Comment by seefood** [comment] 2015-08-02 09:06
Just FYI, I have not been able to use 250000 in months. I do fine with 230400 though, which is close enough.

**Comment by guysoft** [comment] 2015-08-03 08:42
Huh, you got a rigidbot to work at 230400?

**Comment by seefood** [comment] 2015-08-03 09:15
Yeah... Why  not? It's a more standard rs232 speed than 250000...
